# gitlab ci/cd pipeline configuration
image: debian

stages:
  - build
  - test
  - bind

variables:
  DEBIAN_FRONTEND: noninteractive

before_script:
  - apt-get -qq update
  - apt-get -qq install -y --no-install-recommends build-essential cmake time curl virtualenv

# build main library and run test programs
build:
  stage: build
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DBUILD_AUTOTESTS=ON -DBUILD_BENCHMARKS=ON -DBUILD_EXAMPLES=ON -DBUILD_SANDBOX=ON -DCOVERAGE=OFF -DPYTHON=OFF ..
    - make -j4
    - ./benchmark -q -o benchmark.json -f
    - ./xautotest -q -o autotest.json
    #- make check-doc # compile and run documenation checks (e.g. example code in README)
    - make install
    - ldconfig
    - cd ..
    - make -f scripts/liquid_linker_test.mk
  artifacts:
    paths:
      - build/benchmark.json
      - build/autotest.json

# generate coverage report and push to codecov.io
coverage:
  stage: test
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DBUILD_AUTOTESTS=ON -DCOVERAGE=ON -DBUILD_BENCHMARKS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_SANDBOX=OFF -DPYTHON=OFF ..
    - make -j4
    - ./xautotest -q -o autotest.json
    - cd ..
    - virtualenv coverage
    - source coverage/bin/activate
    - pip install codecov-cli gcovr==7.0
    - gcovr --version
    - gcovr --filter="src/.*/src/.*.c" --print-summary | tee coverage.out
    - codecovcli --version
    - codecovcli upload-process -t $CODECOV_TOKEN --git-service gitlab --slug jgaeddert/liquid-dsp
  coverage: '/lines: \d+\.\d+%/'
  artifacts:
    paths:
      - coverage.out
      - build/autotest.json

# test building using legacy environment
legacy:
  stage: test
  script:
    - apt-get -qq install -y --no-install-recommends virtualenv automake autoconf python3-dev
    - virtualenv legacy
    - source legacy/bin/activate
    - pip install numpy "pybind11[global]"
    - ./bootstrap.sh
    - ./configure
    - make -j4
    - make check-doc
    - make install
    - ldconfig
    - make -f scripts/liquid_linker_test.mk

# test cross-compiling with platformio
platformio:
  stage: test
  script:
    - virtualenv platformio
    - source platformio/bin/activate
    - pip install platformio
    - pio ci --lib="." --board=pico examples/platformio_example.c

# compile and run all example programs, timing how long each takes to run
.examples:
  stage: test
  script:
    - make -j4 examples
    - echo '' > time.txt
    - ls examples/*_example | sed -E "s#(.*)#echo '\1' >> time.txt; { time -p ./\1 ; } 2>> time.txt#g" > run_examples.sh
    - /bin/sh run_examples.sh
  artifacts:
    paths: [run_examples.sh, time.txt]

# compile and run autotest programs with valgrind
# NOTE: running all tests on a single-core system can take well over an hour
valgrind:
  stage: test
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - apt-get -qq install -y --no-install-recommends valgrind
    - virtualenv env
    - source env/bin/activate
    - cmake -DBUILD_AUTOTESTS=ON -DCOVERAGE=OFF -DBUILD_BENCHMARKS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_SANDBOX=OFF ..
    - make -j4
    - ../scripts/valgrind_eval.py -output valgrind -test 361 # run a single test initially
    - ../scripts/valgrind_eval.py -output valgrind -summary
  artifacts:
    paths:
      - build/valgrind/*

# cibuildwheel (linux)
linux:
  stage: bind
  when: manual
  image: python:3.12
  # make a docker daemon available for cibuildwheel to use
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  script:
    - curl -sSL https://get.docker.com/ | sh
    - python -m pip install cibuildwheel==2.20.0
    - cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/

# cibuildwheel (macos)
.macos:
  stage: bind
  when: manual
  image: macos-14-xcode-15
  before_script:
    - python3 -m pip install cibuildwheel==2.20.0
  script:
    - python3 -m cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/
  tags:
    - saas-macos-medium-m1

# cibuildwheel (windows)
windows:
  stage: bind
  when: manual
  image: mcr.microsoft.com/windows/servercore:1809
  before_script:
    - choco install python -y --version 3.12.4
    - choco install git.install -y
    - py -m pip install cibuildwheel==2.20.0
  script:
    - py -m cibuildwheel --output-dir wheelhouse --platform windows
  artifacts:
    paths:
      - wheelhouse/
  tags:
    - saas-windows-medium-amd64


