name: Core C CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]

    name: "💦 ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4

    - name: setup (macos)
      if: runner.os == 'macos'
      run: |
        brew update
        brew install cmake pybind11 virtualenv

    - name: setup (linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y --no-install-recommends build-essential cmake pybind11-dev virtualenv python3-dev

    #- name: Setup libfec
    #  run: git clone https://github.com/jgaeddert/libfec.git && cd libfec && ./configure && make && sudo make install

    - name: Build and test
      run: |
        virtualenv env/liquid
        source env/liquid/bin/activate
        python -m pip install pybind11 numpy matplotlib
        mkdir build
        cd build
        cmake -DBUILD_AUTOTESTS=ON -DBUILD_BENCHMARKS=ON -DBUILD_EXAMPLES=ON -DPYTHON=ON ..
        make
        ./xautotest -v -o autotest.json
        python3 -c "import liquid as dsp; print('liquid-dsp python version:',dsp.__version__)"
        #make install
        #ldconfig
        #make check-link
        #make doc-check
        #make bench

    - name: install
      run: |
        cd build
        sudo make install

    - name: check installation (macos)
      if: runner.os == 'macos'
      run: |
        gcc -Wall -O2 -rpath /usr/local/lib -o liquid_linker_test scripts/liquid_linker_test.c -lm -lc -lliquid
        ./liquid_linker_test

    - name: check installation (linux)
      if: runner.os == 'Linux'
      run: |
        sudo ldconfig
        make -f scripts/liquid_linker_test.mk

